# cooldownTime: Time in seconds before the block placement counters are reset
# maxPlacement: Max number of blocks that can be placed without triggering a notification
# notifyReminderThreshold: Once maxPlacement has been reached, send another message each time after this many blocks
# blocks: List of blocks (from Material enum) that are to be monitored. They will all be monitored together as one unit

# monitorLava: Settings for monitoring placement of lava buckets
# enabled: Whether lava placement will be monitored
# amount: Like maxPlacement but for lava
# reminder: Like notifyReminderThreshold but for lava
# message: Like notifyMessage but for lava
# Please note that the time for lava monitoring will be cooldownTime

# notifyMessage: Message sent to players with blockmonitor.notify and the console when too many monitored blocks are placed.
# Replacers:
# %PLAYER%: The player's name
# %NUMBER%: The number of blocks placed
# %TIME%: The value of cooldownTime
# %LOCATION%: The location of the block placed
# locationFormat: The format of the text replaced by %LOCATION%
# Replacers:
# %WORLD%: The world name
# %XCoord%: The X coordinate
# %YCoord%: The Y coordinate
# %ZCoord%: The Z coordinate

cooldownTime: 60
maxPlacement: 10
notifyReminderThreshold: 5

notifyMessage: "&7[&cBlockMonitor&7] &4%PLAYER% has placed %NUMBER% monitored blocks in the past %TIME% seconds. Most recent at %LOCATION%"
locationFormat: "World: %WORLD%, X: %XCoord%, Y: %YCoord%, Z: %ZCoord%"

blocks:
  - PISTON
  - STICKY_PISTON
  
monitorLava:
  enabled: true
  amount: 15
  reminder: 5
  message: "&7[&cBlockMonitor&7] &4%PLAYER% has placed %NUMBER% lava buckets in the past %TIME% seconds. Most recent at %LOCATION%"