# cooldownTime: Time in seconds before the block placement counters are reset
# maxPlacement: Max number of blocks that can be placed without triggering a notification
# blocks: List of blocks (from Material enum) that are to be monitored. They will all be monitored together as one unit
# notifyMessage: Message sent to players with blockmonitor.notify and the console when too many monitored blocks are placed.
# Replacers:
# %PLAYER%: The player's name
# %NUMBER%: The number of blocks placed
# %TIME%: The value of cooldownTime
# %LOCATION%: The location of the block placed

cooldownTime: 60
maxPlacement: 10
notifyMessage: "&7[&cBlockMonitor&7] &4%PLAYER% has placed %NUMBER% monitored blocks in the past %TIME% seconds. Most recent at %LOCATION%"
blocks:
  - PISTON
  - STICKY_PISTON